[package]
name = "registration_processor"
version = "0.1.0"
authors = ["mattl3w1s <matt@csiga.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
