[package]
name = "registration_processor"
version = "0.1.0"
authors = ["mattl3w1s <matt@csiga.org>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-rt = "1"
mongodb = "0.9.2"
bson = "0.14.0"
serde = "1.0.103"
futures = "0.3.4"
fuzzywuzzy = "*"
rand = "*"